# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 201e7d2db47f901e8beb8e208aacb41b05bbe2e452a70a3b6dffcdaaef6646f6b6dadb8602c3fe0e28750f65e3d22ca4bbf7d4cd2743987a74971119bee43d90

test:
  secret_key_base: da88ab593af3f37c5c4f5bf5366353ebe21210c610cdeba0574300740f15a935833331726f6929d47162f07864e63edd023e9f375d2e25fa34cae462918a21e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
